### ISSUE TITLE
Hi, is there additional guide or code in here?

### ISSUE THREAD

**Issue by Boolhwi** [andxet/unity-match-three#1]
I follwed your cloning tutotial and you said complete project is github, 

but I couldn't find any sources about it.

If i just ignored it, let me now.

Thanks.

**Comment by andxet** [comment]
Hello! Yes, this is the complete project, this means that if you follow the tutorial until the end you'll get what is in this repository. But there isn't any more than the tutorial

**Comment by Boolhwi** [comment]
I'm sorry to hear that, your explaination in tutorial was quite specific and good.

Best regards
